### ISSUE TITLE
Update Admonitions

### ISSUE THREAD

**Issue by svx** [ocular-d/styleguide-editorial#17]
Add line explaining that you always should explain in the header of the note what is about.

People scan docs fast, "just" "Note" is not that useful.
Having something like "Note: DESCRIBE CONTENT OF NOTE" is always better.

**Comment by steroman** [comment]
Fixed by: https://github.com/ocular-d/styleguide-editorial/pull/18

**Comment by svx** [comment]
![Screenshot 2020-12-09 at 13 35 23](https://user-images.githubusercontent.com/358860/101630629-6f452180-3a23-11eb-8e1e-cb16c361edbb.png)

We could add here an anchor that would make it more user-friendly and would boost the reading experience 😄

**Comment by steroman** [comment]
Done in https://github.com/ocular-d/styleguide-editorial/pull/19
