### ISSUE TITLE
Add content about image alt text

### ISSUE THREAD

**Issue by svx** [ocular-d/styleguide-editorial#8]
https://support.siteimprove.com/hc/en-gb/articles/115000013031-Accessibility-Image-Alt-text-best-practices

**Comment by steroman** [comment]
I think after your additions and the ones from [PR 14](https://github.com/ocular-d/styleguide-editorial/pull/14) we can consider the issue resolved?

[Sorry, accidentally hit "close issue"]

**Comment by svx** [comment]
Yah, I forgot that I had opened an issue for that :)
